sudo: required

language: python

services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  docker build -t openbabel:python3.6.5 .

script:
  # SMOKE TEST
  - docker run --rm -it openbabel:python3.6.5 python -c 'import openbabel'
